# Generated by Django 3.1.5 on 2021-01-08 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='título',
            new_name='title',
        ),
    ]
